apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  db-endpoint: amRiYzpteXNxbDovL2FwcC1kYi5jNGJtZXN5MGVobWgudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjMzMDYvc3ByaW5nYmFja2VuZA==
  db-username: YWRtaW4=
  db-password: cmVkaGF0MTIz
